---
- hosts: all
  become: true
  tasks:

    - name: "apt-get update"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # 1 Hour

    - name: "apt-get upgrade"
      ansible.builtin.apt:
        #upgrade: safe
        upgrade: full
