---
- hosts: lb
  become: true
  tasks:

    - name: Update NGINX Config
      template:
        src: "./lb_config.j2"
        dest: "/etc/nginx/sites-available/default"
      notify: NGINX Restart

  handlers:

    - name: NGINX Restart
      ansible.builtin.service:
        name: nginx
        state: restarted
