---
- hosts: nginx
  become: true
  tasks:

    - name: "apt-get update"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # 1 Hour

    - name: Install Package NGINX
      ansible.builtin.apt:
        pkg:
          - nginx

    - name: Enable NGINX
      ansible.builtin.systemd:
        name: nginx
        enabled: yes

    - name: Start NGINX
      ansible.builtin.systemd:
        name: nginx
        state: started
